### ISSUE TITLE
Codesandbox for mobx post is not working correctly

### ISSUE THREAD

**Issue by O4epegb** [michalczaplinski/michalczaplinski.github.io#1]
https://codesandbox.io/s/v191wkn77

`view` decorator is a little bit different from blog post and does not work correctly

1) `Observer` component should extend `MyComponent`, not `React.Component`
2) `render` method is different

```
    render() {
      currentlyRenderingComponent = new MyComponent();
      const renderValue = currentlyRenderingComponent.render();
      currentlyRenderingComponent = undefined;
      return renderValue;
    }
```

should be

```
    render() {
      currentlyRenderingComponent = this;
      const renderValue = super.render();
      currentlyRenderingComponent = undefined;
      return renderValue;
    }
```

Thank for the blogpost though, very interesting!

**Comment by michalczaplinski** [comment]
Hi @O4epegb!
Thanks for opening the issue! I was playing around with the sandbox sometime after having written the blog post and I haven't cleaned it up properely! 😅 

I've fixed the sandbox now thanks to your feedback! :)
